import 'package:flutter/material.dart';
import 'package:wholay/styles.dart';
import 'package:wholay/widgets/appWidgets.dart';

class SkillListWidget extends StatefulWidget {
  @override
  _SkillListWidgetState createState() => _SkillListWidgetState();
}

class _SkillListWidgetState extends State<SkillListWidget> {

  @override
  Widget build(BuildContext context) {

    Color _voluntColor        = Colors.green[900];
    Color _voluntShadeColor   = Colors.green[500];
    Color _voluntInactColor   = Colors.green[100];
    Color _needHelpColor      = Colors.orange[900];  
    Color _needHelpShadeColor = Colors.orange[600];  
    Color _needHelpInactColor = Colors.orange[100];

    double _left          = WholaySpace.edgeHorizontal;
    double _right         = 10.0;
    double _top           = 0.0;
    double _bottom        = 5.0;

    return ListView(
      // padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: WholaySpace.edgeHorizontal),
      children: <Widget>[
        Container(
          padding: EdgeInsets.fromLTRB(WholaySpace.edgeHorizontal, 20.0, WholaySpace.edgeHorizontal, 10.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                'ระบุทักษะของคุณ',
                style: secondaryHeaderLabelStyle(context)
              ),
              Text(
                'กรุณาระบุทักษะของคุณที่ต้องการใช้ในการช่วยเหลือผู้อื่นอย่างน้อย 1 อย่าง และทักษะที่คุณต้องการจากผู้อื่นเพื่อช่วยเหลือคุณ (ไม่บังคับ)',
                style: dataInfoLabelStyle(context),
              ),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 5.0, horizontal: WholaySpace.edgeHorizontal),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Container(
                width: 20.0,
                height: 20.0,                  
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: _voluntShadeColor,                    
                  border: Border.all(color: _voluntColor, width: 2.0),
                ),
              ),
              horizontalSpace(20.0),
              Expanded(child: Text('ทักษะที่คุณมีเพื่อช่วยเหลือผู้อื่น (อย่างน้อย 1 อย่าง)', style: minorLabelStyle(context))),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 5.0, horizontal: WholaySpace.edgeHorizontal),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Container(
                width: 20.0,
                height: 20.0,                  
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: _needHelpShadeColor,                    
                  border: Border.all(color: _needHelpColor, width: 2.0),
                ),
              ),
              horizontalSpace(20.0),
              Expanded(child: Text('ทักษะคุณต้องการจากผู้อื่น (ไม่บังคับ)', style: minorLabelStyle(context))),
            ],
          ),
        ),
        verticalSpace(20.0),
        ExpansionTile(
          key: PageStorageKey<String>('study'),
          title: Text('การศึกษา', style: secondaryHeaderLabelStyle(context)),        
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'ครูอาสา',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สร้างสื่อการเรียนรู้',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สอนการบ้าน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สอนดนตรี',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สอนภาษา',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สอนหนังสือเด็ก',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สอนไอทีผู้สูงอายุ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'อ่านหนังสือเสียง',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('sport'),
          title: Text('กีฬา', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'สอนกีฬาประเภทต่างๆ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('agriculture'),
          title: Text('เกษตรกรรม', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'เก็บผลไม้',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เกี่ยวข้าว',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ขยายพันธุ์พืช',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ตอนกิ่ง',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ปลูกผักไฮโดรโฟนิค',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'พรวนดิน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('mechanics'),
          title: Text('งานช่าง', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'ช่างก่อสร้าง',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ช่างไม้',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ซ่อมบ้าน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ซ่อมแอร์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทาสี',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ประปา',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ไฟฟ้า',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ล้างแอร์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สร้างบ้านดิน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('services'),
          title: Text('งานบริการ', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'ทำความสะอาด',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ซักผ้า',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ล้างจาน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ตัดผม',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทำผม',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทำเล็บ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'นวด',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ดูแลสัตว์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'บรรจุ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ลำเลียงสิ่งของ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทำวัสดุอุปกรณ์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทำอาหาร',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('crafts'),
          title: Text('งานฝีมือ', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'งานถัก',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'งานประดิษฐ์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'งานปั้น',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'จัดจาน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'จัดดอกไม้',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ทำของเล่น',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เย็บกระเป๋า',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เย็บตุ๊กตา',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('music'),
          title: Text('ดนตรี', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'ร้องเพลง',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เล่นดนตรีไทย',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เล่นดนตรีสากล',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('technology'),
          title: Text('เทคโนโลยี', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'เขียนโปรแกรม',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ซ่อมคอมพิวเตอร์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ออกแบบเว็บไซต์',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('art culture'),
          title: Text('ศิลปะ วัฒนธรรม', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'งานปั้น',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ถ่ายภาพ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ละครเพื่อเด็ก',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'วาดรูป',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ออกแบบกราฟฟิก',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('public health'),
          title: Text('สาธารณสุข', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'ดูแลเด็ก',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ดูแลผู้สูงอายุ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ฟังสร้างสุข',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'เยี่ยมผู้ป่วย',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ให้คำปรึกษาปัญหาสุขภาพกาย',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ให้คำปรึกษาปัญหาสุขภาพจิต',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

        ExpansionTile(
          key: PageStorageKey<String>('environment'),
          title: Text('สิ่งแวดล้อม', style: secondaryHeaderLabelStyle(context)),
          children: <Widget>[
            DoubleSwitchLabelInput(
              labelText: 'เก็บขยะ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'จัดสวน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ปลูกต้นไม้',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ปลูกปะการัง',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ปลูกป่า',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'ปลูกป่าชายเลน',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'แยกขยะ',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'รีไซเคิล',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
            DoubleSwitchLabelInput(
              labelText: 'สร้างฝาย',
              leftIndent: _left,
              rightIndent: _right,
              topIndent: _top,
              bottomIndent: _bottom,
              fstActiveColor: _voluntColor,
              sndActiveColor: _needHelpColor,
              fstInactiveColor: _voluntInactColor,
              sndInactiveColor: _needHelpInactColor,
              onFstValueChanged: (value) {},
              onSndValueChanged: (value) {},
            ),
          ],
        ),

      ],
    );
    
    // ListView.builder(
    //   itemCount: 3,
    //   itemBuilder: (context, i) {
    //     if (i == 0) {
    //       return Container(
    //         padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: WholaySpace.edgeHorizontal),
    //         child: Column(
    //           mainAxisAlignment: MainAxisAlignment.center,
    //           crossAxisAlignment: CrossAxisAlignment.start,
    //           children: <Widget>[
    //             Text(
    //               'ระบุทักษะของคุณ',
    //               style: secondaryHeaderLabelStyle(context)
    //             ),
    //             Text(
    //               'กรุณาระบุทักษะของคุณที่ต้องการใช้ในการช่วยเหลือผู้อื่นอย่างน้อย 1 อย่าง และทักษะที่คุณต้องการจากผู้อื่นเพื่อช่วยเหลือคุณ (ไม่บังคับ)',
    //               style: dataInfoLabelStyle(context),
    //             ),
    //           ],
    //         ),
    //       );
    //     } else {
    //       return Text('List ${i}');
    //     }
    //   },
    // );
    
    
    // CustomScrollView(
    //   slivers: <Widget>[
    //     SliverList(
    //       delegate: SliverChildListDelegate([
    //           Container(
    //             padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: WholaySpace.edgeHorizontal),
    //             child: Column(
    //               mainAxisAlignment: MainAxisAlignment.center,
    //               crossAxisAlignment: CrossAxisAlignment.start,
    //               children: <Widget>[
    //                 Text(
    //                   'ระบุทักษะของคุณ',
    //                   style: secondaryHeaderLabelStyle(context)
    //                 ),
    //                 Text(
    //                   'กรุณาระบุทักษะของคุณที่ต้องการใช้ในการช่วยเหลือผู้อื่นอย่างน้อย 1 อย่าง และทักษะที่คุณต้องการให้ผู้อื่นช่วยเหลือคุณ (ไม่บังคับ)',
    //                   style: dataInfoLabelStyle(context),
    //                 ),
    //                 verticalSpace(15.0),
    //               ],
    //             ),
    //           ),
    //       ]),
    //     )
    //   ],
    // );
  }
}